language: php

sudo: false

# Test main supported versions of PHP against latest WP. 5.2 is min supported PHP version.
php:
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0  WC_VERSION=3.4.5

# Additonal tests against stable PHP (min recommended version is 5.6) and past supported versions of WP.
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1 WC_VERSION=2.6.14
  - php: 7.1
    env: WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=3.4.5
  - name: "WC E2E 3.0.0"
    env: WP_VERSION=latest WP_MULTISITE=0 RUN_E2E=1 E2E_FOLDER='core_e2e_tests'
    php: 7.2
    before_script: true
    addons:
      chrome: stable
      apt:
        packages:
          - nginx
    script:
      - git clone --branch=master git@github.com:woocommerce/extensions-e2e-core-tests.git /tmp/tests
      - mkdir -p $E2E_FOLDER
      - mv -v /tmp/tests/* "$E2E_FOLDER/"
      - export PATH="$HOME/.composer/vendor/bin:$PATH"
      - export NODE_CONFIG='{"users":{"admin":{"username":"admin","password":"password"},"customer":{"username":"customer","password":"password"}}}'
      - $E2E_FOLDER/bin/install.sh woocommerce_test root '' localhost $WP_VERSION
      - $E2E_FOLDER/bin/travis.sh before
      - $E2E_FOLDER/bin/run-e2e-CI.sh
      - tests/bin/run-e2e-CI.sh

before_script:
  - phpenv config-rm xdebug.ini
  - bash tests/bin/install.sh wc_stripe_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

#save node_modules to speed up build
cache:
      directories:
              - node_modules

after_script:
  - bash tests/bin/travis.sh after
