version: "3"

services:
  wordpress:
    build: ./docker/wordpress_xdebug
    image: wordpress-xdebug
    container_name: woocommerce_stripe_wordpress_copy
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "8084:80"
    env_file:
      - default.env
    volumes:
      - ./docker/wordpress:/var/www/html/
      - ./docker/logs/apache2/:/var/log/apache2
      - .:/var/www/html/wp-content/plugins/woocommerce-gateway-stripe
      - ./docker/dev-php.ini:/usr/local/etc/php/conf.d/dev-php.ini
      - ./docker/bin:/var/scripts
  db:
    container_name: woocommerce_stripe_mysql_copy
    image: mysql:5.7
    ports:
      - "5679:3306"
    env_file:
      - default.env
    volumes:
      - ./docker/data:/var/lib/mysql
  phpMyAdmin:
    container_name: woocommerce_stripe_phpmyadmin_copy
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8085:80"
    env_file:
      - default.env